export const NO_PROP_VALUE = "__none__";

const clippyFields = [
  {
    title: "Behavior",
    fields: [
      {
        key: "mode",
        label: "Animation",
        type: "select",
        options: ["idle", "wave", "celebrate", "spin", "point"],
        catalogKey: "modes",
      },
      {
        key: "expression",
        label: "Expression",
        type: "select",
        options: ["neutral", "happy", "focused", "surprised"],
      },
      {
        key: "propName",
        label: "Prop",
        type: "select",
        options: [NO_PROP_VALUE],
        catalogKey: "props",
      },
      {
        key: "speed",
        label: "Playback Speed",
        type: "range",
        min: 0.2,
        max: 2.5,
        step: 0.05,
        format: "speed",
      },
    ],
  },
  {
    title: "Shape",
    fields: [
      { key: "scale", label: "Body Scale", type: "range", min: 0.35, max: 2.2, step: 0.01 },
      { key: "wireThickness", label: "Wire Thickness", type: "range", min: 0.35, max: 3.2, step: 0.01 },
      { key: "headScale", label: "Head Scale", type: "range", min: 0.7, max: 1.8, step: 0.01 },
      { key: "headX", label: "Head X", type: "range", min: -0.8, max: 0.8, step: 0.01 },
      { key: "headY", label: "Head Y", type: "range", min: -0.7, max: 0.7, step: 0.01 },
      { key: "headZ", label: "Head Z", type: "range", min: -0.45, max: 0.8, step: 0.01 },
      { key: "eyeScale", label: "Eye Scale", type: "range", min: 0.45, max: 3.2, step: 0.01 },
      { key: "eyeSpacing", label: "Eye Spacing", type: "range", min: 0.22, max: 0.9, step: 0.005 },
      { key: "pupilScale", label: "Pupil Scale", type: "range", min: 0.4, max: 1.9, step: 0.01 },
      { key: "browTilt", label: "Brow Tilt", type: "range", min: -0.8, max: 0.8, step: 0.01 },
      { key: "browLift", label: "Brow Lift", type: "range", min: -0.35, max: 0.35, step: 0.01 },
      { key: "browScale", label: "Brow Scale", type: "range", min: 0.4, max: 2.2, step: 0.01 },
      { key: "browThickness", label: "Brow Thickness", type: "range", min: 0.35, max: 3.2, step: 0.01 },
      { key: "mouthWidth", label: "Mouth Width", type: "range", min: 0.55, max: 1.8, step: 0.01 },
      { key: "mouthHeight", label: "Mouth Height", type: "range", min: 0.35, max: 1.85, step: 0.01 },
      { key: "armSpread", label: "Arm Spread", type: "range", min: 1.1, max: 2.9, step: 0.01 },
      { key: "armY", label: "Arm Height", type: "range", min: -2, max: 0, step: 0.01 },
    ],
  },
  {
    title: "Materials",
    fields: [
      { key: "metalColor", label: "Metal", type: "color" },
      { key: "darkColor", label: "Dark", type: "color" },
      { key: "eyeColor", label: "Eye White", type: "color" },
      { key: "glowColor", label: "Glow", type: "color" },
      { key: "metalness", label: "Metalness", type: "range", min: 0, max: 1, step: 0.01 },
      { key: "roughness", label: "Roughness", type: "range", min: 0, max: 1, step: 0.01 },
      { key: "clearcoat", label: "Clearcoat", type: "range", min: 0, max: 1, step: 0.01 },
      { key: "clearcoatRoughness", label: "Clearcoat Roughness", type: "range", min: 0, max: 1, step: 0.01 },
      { key: "glowIntensity", label: "Glow Intensity", type: "range", min: 0, max: 0.75, step: 0.01 },
    ],
  },
];

const pinFields = [
  {
    title: "Behavior",
    fields: [
      {
        key: "mode",
        label: "Animation",
        type: "select",
        options: ["idle", "bob", "wave", "spin", "celebrate"],
      },
      {
        key: "expression",
        label: "Expression",
        type: "select",
        options: ["neutral", "smile", "determined", "startled"],
      },
      {
        key: "speed",
        label: "Playback Speed",
        type: "range",
        min: 0.2,
        max: 2.5,
        step: 0.05,
        format: "speed",
      },
    ],
  },
  {
    title: "Shape",
    fields: [
      { key: "scale", label: "Body Scale", type: "range", min: 0.4, max: 2.2, step: 0.01 },
      { key: "wireThickness", label: "Pin Thickness", type: "range", min: 0.014, max: 0.08, step: 0.001 },
      { key: "crownWidth", label: "Head Diameter", type: "range", min: 0.8, max: 2.8, step: 0.01 },
      { key: "legHeight", label: "Pin Length", type: "range", min: 0.35, max: 2.2, step: 0.01 },
      { key: "legSplay", label: "Pin Lean", type: "range", min: -0.6, max: 0.6, step: 0.01 },
      { key: "depthCurve", label: "Head Dome", type: "range", min: 0, max: 1, step: 0.01 },
      { key: "faceY", label: "Face Y", type: "range", min: -0.6, max: 0.8, step: 0.01 },
      { key: "faceZ", label: "Face Z", type: "range", min: -0.25, max: 0.45, step: 0.01 },
      { key: "eyeScale", label: "Eye Scale", type: "range", min: 0.6, max: 2.3, step: 0.01 },
      { key: "eyeSpacing", label: "Eye Spacing", type: "range", min: 0.1, max: 0.38, step: 0.005 },
      { key: "pupilScale", label: "Pupil Scale", type: "range", min: 0.45, max: 1.8, step: 0.01 },
      { key: "browTilt", label: "Brow Tilt", type: "range", min: -0.9, max: 0.9, step: 0.01 },
      { key: "browLift", label: "Brow Lift", type: "range", min: -0.35, max: 0.35, step: 0.01 },
      { key: "mouthWidth", label: "Mouth Width", type: "range", min: 0.5, max: 2, step: 0.01 },
      { key: "mouthCurve", label: "Mouth Curve", type: "range", min: -0.9, max: 0.9, step: 0.01 },
    ],
  },
  {
    title: "Materials",
    fields: [
      { key: "metalColor", label: "Metal", type: "color" },
      { key: "darkColor", label: "Dark", type: "color" },
      { key: "eyeColor", label: "Eye White", type: "color" },
      { key: "faceColor", label: "Cap Color", type: "color" },
      { key: "glowColor", label: "Glow", type: "color" },
      { key: "metalness", label: "Metalness", type: "range", min: 0, max: 1, step: 0.01 },
      { key: "roughness", label: "Roughness", type: "range", min: 0, max: 1, step: 0.01 },
      { key: "clearcoat", label: "Clearcoat", type: "range", min: 0, max: 1, step: 0.01 },
      { key: "clearcoatRoughness", label: "Clearcoat Roughness", type: "range", min: 0, max: 1, step: 0.01 },
      { key: "glowIntensity", label: "Glow Intensity", type: "range", min: 0, max: 1, step: 0.01 },
    ],
  },
];

export const AVATAR_DEFINITIONS = {
  clippy: {
    id: "clippy",
    label: "Clippy",
    description: "Classic assistant paperclip with office props and expression controls.",
    engine: "clippy",
    scenePreset: "clippy",
    controls: clippyFields,
    defaultState: {
      mode: "idle",
      expression: "neutral",
      propName: NO_PROP_VALUE,
      speed: 1,

      scale: 0.54,
      wireThickness: 1.79,
      headScale: 1,
      headX: 0.36,
      headY: -0.33,
      headZ: 0,
      eyeScale: 2.4,
      eyeSpacing: 0.54,
      pupilScale: 1,
      browTilt: 0,
      browLift: 0,
      browScale: 1.36,
      browThickness: 1,
      mouthWidth: 1,
      mouthHeight: 1,
      armSpread: 1.95,
      armY: -1.12,

      metalColor: "#e7edf6",
      darkColor: "#0f172a",
      eyeColor: "#f8fafc",
      glowColor: "#1f2a38",
      metalness: 0.46,
      roughness: 0.18,
      clearcoat: 0.9,
      clearcoatRoughness: 0.14,
      glowIntensity: 0.12,
    },
  },
  pushy: {
    id: "pushy",
    label: "Pushy",
    description: "Push pin avatar with layered cap profile and animated expressions.",
    engine: "thumbtack",
    profile: "pushy",
    scenePreset: "pin",
    controls: pinFields,
    defaultState: {
      mode: "idle",
      expression: "neutral",
      speed: 1,

      scale: 0.74,
      wireThickness: 0.03,
      crownWidth: 1.36,
      legHeight: 0.46,
      legSplay: 0,
      depthCurve: 0.52,
      faceY: 0,
      faceZ: 0,
      eyeScale: 1,
      eyeSpacing: 0.19,
      pupilScale: 1,
      browTilt: 0,
      browLift: 0,
      mouthWidth: 1.07,
      mouthCurve: -0.7,

      metalColor: "#cdd5df",
      darkColor: "#111827",
      eyeColor: "#fffaf0",
      faceColor: "#ef4444",
      glowColor: "#2dd4bf",
      metalness: 0.82,
      roughness: 0.2,
      clearcoat: 0.86,
      clearcoatRoughness: 0.16,
      glowIntensity: 0.1,
    },
  },
  tacky: {
    id: "tacky",
    label: "Tacky",
    description: "Thumb tack mascot with rounded cap profile and playful animation.",
    engine: "thumbtack",
    profile: "tacky",
    scenePreset: "pin",
    controls: pinFields,
    defaultState: {
      mode: "idle",
      expression: "neutral",
      speed: 1,

      scale: 0.74,
      wireThickness: 0.03,
      crownWidth: 1.36,
      legHeight: 0.46,
      legSplay: 0,
      depthCurve: 0.52,
      faceY: 0,
      faceZ: 0,
      eyeScale: 1,
      eyeSpacing: 0.19,
      pupilScale: 1,
      browTilt: 0,
      browLift: 0,
      mouthWidth: 1.07,
      mouthCurve: -0.7,

      metalColor: "#cdd5df",
      darkColor: "#111827",
      eyeColor: "#fffaf0",
      faceColor: "#facc15",
      glowColor: "#2dd4bf",
      metalness: 0.82,
      roughness: 0.2,
      clearcoat: 0.86,
      clearcoatRoughness: 0.16,
      glowIntensity: 0.1,
    },
  },
};

export const AVATAR_ORDER = ["clippy", "pushy", "tacky"];

export const SCENE_PRESETS = {
  clippy: {
    fogColor: 0xe8dcc9,
    fogNear: 9.5,
    fogFar: 19.5,
    camera: [0.2, 1.35, 8.9],
    orbitTarget: [0, 0.45, 0],
  },
  pin: {
    fogColor: 0xf0dfc2,
    fogNear: 8.5,
    fogFar: 20,
    camera: [0.28, -1.45, 5.2],
    orbitTarget: [0, -2.02, 0],
  },
};

export const PIN_STAGE_TOP_Y = -2.67;
